version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "24401:24401"
    volumes:
      - ./backend:/usr/src/app
      - ./frontend/public:/usr/src/app/public

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./api:/usr/src/app