services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "24401:24401"
    volumes:
      - ./backend:/usr/src/app
      - ./frontend/public:/usr/src/frontend/public
    networks:
      - web

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "24402:24402"
    volumes:
      - ./api:/usr/src/app
    networks:
      - web

networks:
  web:
    external: true